### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by FutureElement** [yalishizhude/api-document#15]
[root@localhost bin]# cnpm start

> api-document-server@1.0.0 start /home/api-document
> node ./bin/www

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/api-document/node_modules/_bson@0.2.22@bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
[2017-08-16 16:02:45.630] [ERROR] console - js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by yalishizhude** [comment]
检查一下你的node版本，目前通过测试的是node4的版本，更高版本上运行可能存在问题
